version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    groups:
      # Group updates for actions owned by GitHub into one PR: they often update
      # them all at once to bump the Node.JS version.
      github:
        patterns:
          - "actions/*"
